# importar el framework fastapi al entorno de trabajo
from fastapi import FastAPI

# crear el objeto a partir de la clase
APIGetCD = FastAPI()
APITaylor = FastAPI()

# utlizar la funcion get con el objeto
@APIGetCD.get("/CD")

# crear la funcion asincrona "imprimir"
async def CD(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Midnights", "artista":"Taylor Swift", "genero":"Pop"}],
            2:[{"nombre":"reputation", "artista":"Taylor Swift", "genero":"Pop"}],
            3:[{"nombre":"Lover", "artista":"Taylor Swift", "genero":"Pop"}],
            4:[{"nombre":"1989", "artista":"Taylor Swift", "genero":"Pop"}],
            5:[{"nombre":"Taylor Swift", "artista":"Taylor Swift", "genero":"Country"}],
            6:[{"nombre":"Fearless", "artista":"Taylor Swift", "genero":"Country"}],
            7:[{"nombre":"Speak Now", "artista":"Taylor Swift", "genero":"Country"}],
            8:[{"nombre":"Red", "artista":"Taylor Swift", "genero":"Pop"}],
            9:[{"nombre":"folklore", "artista":"Taylor Swift", "genero":"Indie"}],
            10:[{"nombre":"evermore", "artista":"Taylor Swift", "genero":"Indie"}],
            11:[{"nombre":"Did you know that there's a tunnel under Ocean Blvd", "artista":"Lana del Rey", "genero":"Alternative"}],
            12:[{"nombre":"Blue Banisters", "artista":"Lana del Rey", "genero":"Alternative"}],
            13:[{"nombre":"Chemtrails Over The Country Club", "artista":"Lana del Rey", "genero":"Alternative"}],
            14:[{"nombre":"Norman Fucking Rockwell", "artista":"Lana del Rey", "genero":"Alternative"}],
            15:[{"nombre":"Lust For Life", "artista":"Lana del Rey", "genero":"Alternative"}],
            16:[{"nombre":"Honeymoon", "artista":"Lana del Rey", "genero":"Alternative"}],
            17:[{"nombre":"Ultraviolence", "artista":"Lana del Rey", "genero":"Alternative"}],
            18:[{"nombre":"Born to Die", "artista":"Lana del Rey", "genero":"Alternative"}],
            19:[{"nombre":"Paradise", "artista":"Lana del Rey", "genero":"Alternative"}],
            20:[{"nombre":"Pure Heroine", "artista":"Lorde", "genero":"Alternative"}],
            21:[{"nombre":"The Love Club", "artista":"Lorde", "genero":"Alternative"}],
            22:[{"nombre":"Melodrama", "artista":"Lorde", "genero":"Pop"}],
            23:[{"nombre":"Solar Power", "artista":"Lorde", "genero":"Alternative"}],
            24:[{"nombre":"Bubblebath", "artista":"Poppy", "genero":"Pop"}],
            25:[{"nombre":"Poppy.Computer", "artista":"Poppy", "genero":"Pop"}],
            26:[{"nombre":"Am I a Girl?", "artista":"Poppy", "genero":"Pop"}],
            27:[{"nombre":"Choke", "artista":"Poppy", "genero":"Experimental"}],
            28:[{"nombre":"I Disagree", "artista":"Poppy", "genero":"Rock"}],
            29:[{"nombre":"A Very Poppy Christmas", "artista":"Poppy", "genero":"Rock"}],
            30:[{"nombre":"EAT (NXT Soundtrack)", "artista":"Poppy", "genero":"Rock"}],
            31:[{"nombre":"Flux", "artista":"Poppy", "genero":"Rock"}],
            32:[{"nombre":"Stagger", "artista":"Poppy", "genero":"Rock"}],
            33:[{"nombre":"Knockoff", "artista":"Poppy", "genero":"Rock"}],
            34:[{"nombre":"World War Joy", "artista":"The Chainsmokers", "genero":"Pop"}],
            35:[{"nombre":"So Far So Good", "artista":"The Chainsmokers", "genero":"Pop"}],
            36:[{"nombre":"Bouquet", "artista":"The Chainsmokers", "genero":"Pop"}],
            37:[{"nombre":"Collage", "artista":"The Chainsmokers", "genero":"Pop"}],
            38:[{"nombre":"Memories...Do Not Open", "artista":"The Chainsmokers", "genero":"Pop"}],
            39:[{"nombre":"Sick Boy", "artista":"The Chainsmokers", "genero":"Pop"}],
            40:[{"nombre":"Los Angeles", "artista":"ROSALIA", "genero":"Indie"}],
            41:[{"nombre":"El Mal Querer", "artista":"ROSALIA", "genero":"Alternative"}],
            42:[{"nombre":"MOTOMAMI", "artista":"ROSALIA", "genero":"Pop"}],
            43:[{"nombre":"MTV Unplugged", "artista":"Katy Perry", "genero":"Pop"}],
            44:[{"nombre":"One Of The Boys", "artista":"Katy Perry", "genero":"Pop"}],
            45:[{"nombre":"Teenage Dreams", "artista":"Katy Perry", "genero":"Pop"}],
            46:[{"nombre":"PRISM", "artista":"Katy Perry", "genero":"Pop"}],
            47:[{"nombre":"Witness", "artista":"Katy Perry", "genero":"Pop"}],
            48:[{"nombre":"Smile", "artista":"Katy Perry", "genero":"Pop"}],
            49:[{"nombre":"Glass Animals", "artista":"Glass Animals", "genero":"Indie"}],
            50:[{"nombre":"ZABA", "artista":"Glass Animals", "genero":"Indie"}],
            51:[{"nombre":"How To Be A Human Being", "artista":"Glass Animals", "genero":"Indie"}],
            52:[{"nombre":"Dreamland", "artista":"Glass Animals", "genero":"Pop"}],
            53:[{"nombre":"I Don't Wanna Grow Up", "artista":"Bebe Rexha", "genero":"Pop"}],
            54:[{"nombre":"All Your Fault Pt. 1", "artista":"Bebe Rexha", "genero":"Pop"}],
            55:[{"nombre":"All Your Fault Pt. 2", "artista":"Bebe Rexha", "genero":"Pop"}],
            56:[{"nombre":"Expectations", "artista":"Bebe Rexha", "genero":"Pop"}],
            57:[{"nombre":"Better Mistakes", "artista":"Bebe Rexha", "genero":"Pop"}],
            58:[{"nombre":"Bebe", "artista":"Bebe Rexha", "genero":"Pop"}],
            59:[{"nombre":"For You", "artista":"Selena Gomez", "genero":"Pop"}],
            60:[{"nombre":"Kiss & Tell", "artista":"Selena Gomez", "genero":"Pop"}],
            61:[{"nombre":"A Year Without Rain", "artista":"Selena Gomez", "genero":"Pop"}],
            62:[{"nombre":"When the Sun Goes Down", "artista":"Selena Gomez", "genero":"Pop"}],
            63:[{"nombre":"Stars Dance", "artista":"Selena Gomez", "genero":"Pop"}],
            64:[{"nombre":"Revival", "artista":"Selena Gomez", "genero":"Pop"}],
            65:[{"nombre":"Rare", "artista":"Selena Gomez", "genero":"Pop"}],
            66:[{"nombre":"Revelacion", "artista":"Selena Gomez", "genero":"Latin"}],
            67:[{"nombre":"Whatever People Say I Am, That's What I Am Not", "artista":"Arctic Monkeys", "genero":"Indie"}],
            68:[{"nombre":"Who The Fuck Are Arctic Monkeys?", "artista":"Arctic Monkeys", "genero":"Indie"}],
            69:[{"nombre":"Brainstorm", "artista":"Arctic Monkeys", "genero":"Indie"}],
            70:[{"nombre":"Favourite Worst Nightmare", "artista":"Arctic Monkeys", "genero":"Indie"}],
            71:[{"nombre":"Fluorescent Adolescent", "artista":"Arctic Monkeys", "genero":"Indie"}],
            72:[{"nombre":"Teddy Picker", "artista":"Arctic Monkeys", "genero":"Indie"}],
            73:[{"nombre":"Humbug", "artista":"Arctic Monkeys", "genero":"Indie"}],
            74:[{"nombre":"Cornerstone", "artista":"Arctic Monkeys", "genero":"Indie"}],
            75:[{"nombre":"My Propeller", "artista":"Arctic Monkeys", "genero":"Indie"}],
            76:[{"nombre":"Suck It and See", "artista":"Arctic Monkeys", "genero":"Indie"}],
            77:[{"nombre":"AM", "artista":"Arctic Monkeys", "genero":"Indie"}],
            78:[{"nombre":"Tranquility Base Hotel & Casino", "artista":"Arctic Monkeys", "genero":"Indie"}],
            79:[{"nombre":"The Car", "artista":"Arctic Monkeys", "genero":"Indie"}],
            80:[{"nombre":"Aprendiendo a Aprender", "artista":"Carla Morrison", "genero":"Alternative"}],
            81:[{"nombre":"Mientras Tu Dormias", "artista":"Carla Morrison", "genero":"Alternative"}],
            82:[{"nombre":"Dejenme Llorar", "artista":"Carla Morrison", "genero":"Alternative"}],
            83:[{"nombre":"Jugando en Serio", "artista":"Carla Morrison", "genero":"Alternative"}],
            84:[{"nombre":"Amor Supremo", "artista":"Carla Morrison", "genero":"Alternative"}],
            85:[{"nombre":"El Renacimiento", "artista":"Carla Morrison", "genero":"Alternative"}],
            86:[{"nombre":"The Slow Rush", "artista":"Tame Impala", "genero":"Alternative"}],
            87:[{"nombre":"Currents", "artista":"Tame Impala", "genero":"Alternative"}],
            88:[{"nombre":"Lonerism", "artista":"Tame Impala", "genero":"Alternative"}],
            89:[{"nombre":"InnerSpeaker", "artista":"Tame Impala", "genero":"Alternative"}],
            90:[{"nombre":"Sentio", "artista":"Martin Garrix", "genero":"Electronic"}],
            91:[{"nombre":"Martin Garrix Presents STMPD RCRDS, Vol. 001", "artista":"Martin Garrix", "genero":"Electronic"}],
            92:[{"nombre":"2019 Remixed", "artista":"Martin Garrix", "genero":"Electronic"}],
            93:[{"nombre":"Gold Skies", "artista":"Martin Garrix", "genero":"Electronic"}],
            94:[{"nombre":"Seven", "artista":"Martin Garrix", "genero":"Electronic"}],
            95:[{"nombre":"Joytime", "artista":"Marshmello", "genero":"Electronic"}],
            96:[{"nombre":"Joytime II", "artista":"Marshmello", "genero":"Electronic"}],
            97:[{"nombre":"Joytime III", "artista":"Marshmello", "genero":"Electronic"}],
            98:[{"nombre":"Shockwave", "artista":"Marshmello", "genero":"Electronic"}],
            99:[{"nombre":"Mellokillaz", "artista":"Marshmello", "genero":"Electronic"}],
            100:[{"nombre":"With Hearts As One", "artista":"Hillsong United", "genero":"Christian"}],
            101:[{"nombre":"Of Dirt And Grace", "artista":"Hillsong United", "genero":"Christian"}],
            102:[{"nombre":"The White Album", "artista":"Hillsong United", "genero":"Christian"}],
            103:[{"nombre":"Everyday (Live)", "artista":"Hillsong United", "genero":"Christian"}],
            104:[{"nombre":"Best Friend: United Live", "artista":"Hillsong United", "genero":"Christian"}],
            105:[{"nombre":"King of Magesty", "artista":"Hillsong United", "genero":"Christian"}],
            106:[{"nombre":"To The Ends Of The Earth", "artista":"Hillsong United", "genero":"Christian"}],
            107:[{"nombre":"More Than Life (Live)", "artista":"Hillsong United", "genero":"Christian"}],
            108:[{"nombre":"Look To You", "artista":"Hillsong United", "genero":"Christian"}],
            109:[{"nombre":"United We Stand", "artista":"Hillsong United", "genero":"Christian"}],
            110:[{"nombre":"Across The Earth: Tear Down The Walls", "artista":"Hillsong United", "genero":"Christian"}],
            111:[{"nombre":"Live In Miami", "artista":"Hillsong United", "genero":"Christian"}],
            112:[{"nombre":"People (Live)", "artista":"Hillsong United", "genero":"Christian"}],
            113:[{"nombre":"All Of The Above", "artista":"Hillsong United", "genero":"Christian"}],
            114:[{"nombre":"Aftermath", "artista":"Hillsong United", "genero":"Christian"}],
            115:[{"nombre":"Zion", "artista":"Hillsong United", "genero":"Christian"}],
            116:[{"nombre":"Empires", "artista":"Hillsong United", "genero":"Christian"}],
            117:[{"nombre":"Wonder", "artista":"Hillsong United", "genero":"Christian"}],
            118:[{"nombre":"(in the meantime)", "artista":"Hillsong United", "genero":"Christian"}],
            119:[{"nombre":"(in the meantime) Vol. II", "artista":"Hillsong United", "genero":"Christian"}],
            120:[{"nombre":"Are We There Yet?", "artista":"Hillsong United", "genero":"Christian"}],
            121:[{"nombre":"LAS QUE NO IBAN A SALIR", "artista":"Bad Bunny", "genero":"Latin"}],
            122:[{"nombre":"X 100PRE", "artista":"Bad Bunny", "genero":"Latin"}],
            123:[{"nombre":"OASIS", "artista":"Bad Bunny", "genero":"Latin"}],
            124:[{"nombre":"YHLQMDLG", "artista":"Bad Bunny", "genero":"Latin"}],
            125:[{"nombre":"EL ULTIMO TOUR DEL MUNDO", "artista":"Bad Bunny", "genero":"Latin"}],
            126:[{"nombre":"Un Verano Sin Ti", "artista":"Bad Bunny", "genero":"Latin"}],
            127:[{"nombre":"Todo Es Diferente", "artista":"Natanael Cano", "genero":"Latin"}],
            128:[{"nombre":"Corridos Tumbados", "artista":"Natanael Cano", "genero":"Latin"}],
            129:[{"nombre":"Trap Tumbado", "artista":"Natanael Cano", "genero":"Latin"}],
            130:[{"nombre":"Soy El Nata", "artista":"Natanael Cano", "genero":"Latin"}],
            131:[{"nombre":"Las 3 Torres", "artista":"Natanael Cano", "genero":"Latin"}],
            132:[{"nombre":"Mi Nuevo Yo", "artista":"Natanael Cano", "genero":"Latin"}],
            133:[{"nombre":"Nata", "artista":"Natanael Cano", "genero":"Latin"}],
            134:[{"nombre":"A Mis 20", "artista":"Natanael Cano", "genero":"Latin"}],
            135:[{"nombre":"NataKong", "artista":"Natanael Cano", "genero":"Latin"}],
            136:[{"nombre":"Nata Montana", "artista":"Natanael Cano", "genero":"Latin"}],
            137:[{"nombre":"MAÑANA SERA BONITO", "artista":"Karol G", "genero":"Latin"}],
            138:[{"nombre":"KG0516", "artista":"Karol G", "genero":"Latin"}],
            139:[{"nombre":"OCEAN", "artista":"Karol G", "genero":"Latin"}],
            140:[{"nombre":"Unstoppable", "artista":"Karol G", "genero":"Latin"}],
            141:[{"nombre":"72 Seasons", "artista":"Metallica", "genero":"Metal"}],
            142:[{"nombre":"Metallica Live At Woodstck '94", "artista":"Metallica", "genero":"Metal"}],
            143:[{"nombre":"The Metallica Blacklist", "artista":"Metallica", "genero":"Metal"}],
            144:[{"nombre":"Hardwired...To Self-Destruct", "artista":"Metallica", "genero":"Metal"}],
            145:[{"nombre":"Death Magnetic", "artista":"Metallica", "genero":"Metal"}],
            146:[{"nombre":"St. Anger", "artista":"Metallica", "genero":"Metal"}],
            147:[{"nombre":"Reload", "artista":"Metallica", "genero":"Metal"}],
            148:[{"nombre":"Load", "artista":"Metallica", "genero":"Metal"}],
            149:[{"nombre":"Remaining Memories: The Interview", "artista":"Metallica", "genero":"Metal"}],
            150:[{"nombre":"Live S**t: Binge & Purge", "artista":"Metallica", "genero":"Metal"}],
            151:[{"nombre":"Metallica", "artista":"Metallica", "genero":"Metal"}],
            152:[{"nombre":"...And Justice For All", "artista":"Metallica", "genero":"Metal"}],
            153:[{"nombre":"Master of Puppets", "artista":"Metallica", "genero":"Metal"}],
            154:[{"nombre":"Ride The Lightning", "artista":"Metallica", "genero":"Metal"}],
            155:[{"nombre":"UTOPIA", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            156:[{"nombre":"ASTROWORLD", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            157:[{"nombre":"Huncho Jack, Jack Huncho", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            158:[{"nombre":"Birds in the Trap Sing McKnight", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            159:[{"nombre":"Rodeo (Expanded Edition)", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            160:[{"nombre":"JACKBOYS", "artista":"Travis Scott", "genero":"Hip-Hop"}],
            161:[{"nombre":"Her Loss", "artista":"Drake", "genero":"Hip-Hop"}],
            162:[{"nombre":"Honestly, Nevermind", "artista":"Drake", "genero":"Hip-Hop"}],
            163:[{"nombre":"Certified Lover Boy", "artista":"Drake", "genero":"Hip-Hop"}],
            164:[{"nombre":"Scorpion", "artista":"Drake", "genero":"Hip-Hop"}],
            165:[{"nombre":"More Life", "artista":"Drake", "genero":"Hip-Hop"}],
            166:[{"nombre":"Views", "artista":"Drake", "genero":"Hip-Hop"}],
            167:[{"nombre":"If You're Reading This It's Too Late", "artista":"Drake", "genero":"Hip-Hop"}],
            168:[{"nombre":"Nothing Was The Same", "artista":"Drake", "genero":"Hip-Hop"}],
            169:[{"nombre":"Take Care (Deluxe)", "artista":"Drake", "genero":"Hip-Hop"}],
            170:[{"nombre":"Thank Me Later", "artista":"Drake", "genero":"Hip-Hop"}],
            171:[{"nombre":"Dark Lane Demo Tapes", "artista":"Drake", "genero":"Hip-Hop"}],
            172:[{"nombre":"Care Package", "artista":"Drake", "genero":"Hip-Hop"}],
            173:[{"nombre":"What a Time To Be Alive", "artista":"Drake", "genero":"Hip-Hop"}],
            174:[{"nombre":"So Far Gone", "artista":"Drake", "genero":"Hip-Hop"}],
            175:[{"nombre":"Tarzan (Banda Sonora Original)", "artista":"Various Artists", "genero":"Soundtrack"}],
            176:[{"nombre":"UNDERTALE Soundtrack", "artista":"Various Artists", "genero":"Soundtrack"}],
            177:[{"nombre":"Sing 2 (Original Motion Picture Soundtrack)", "artista":"Various Artists", "genero":"Soundtrack"}],
            178:[{"nombre":"A Star Is Born Soundtrack", "artista":"Lady Gaga", "genero":"Soundtrack"}],
            179:[{"nombre":"Euphoria (Original Score from the HBO Series)", "artista":"Labirinth", "genero":"Soundtrack"}],
            180:[{"nombre":"Love For Sale (Deluxe)", "artista":"Lady Gaga", "genero":"Jazz"}],
            181:[{"nombre":"Chromatica", "artista":"Lady Gaga", "genero":"Pop"}],
            182:[{"nombre":"Joanne", "artista":"Lady Gaga", "genero":"Indie"}],
            183:[{"nombre":"Cheek to Cheek", "artista":"Lady Gaga", "genero":"Jazz"},],
            184:[{"nombre":"ARTPOP", "artista":"Lady Gaga", "genero":"Pop"}],
            185:[{"nombre":"Born this Way", "artista":"Lady Gaga", "genero":"Pop"},],
            186:[{"nombre":"The Fame Monster", "artista":"Lady Gaga", "genero":"Pop"}],
            187:[{"nombre":"The Fame", "artista":"Lady Gaga", "genero":"Pop"}],
            188:[{"nombre":"Like a Prayer", "artista":"Madonna", "genero":"Pop"},],
            189:[{"nombre":"La La Land (Original Motion Picture Soundtrack)", "artista":"Various Artists", "genero":"Soundtrack"}],
            190:[{"nombre":"Mexico And Mariachis", "artista":"Various Artists", "genero":"Soundtrack"}],
            191:[{"nombre":"Minecraft - Volume Alpha", "artista":"C418", "genero":"Soundtrack"}],
            192:[{"nombre":"Sonic Frontiers Original Soundtrack", "artista":"SEGA", "genero":"Soundtrack"}],
            193:[{"nombre":"Mamma Mia! The Movie Soundtrack", "artista":"Various Artists", "genero":"Soundtrack"}],
            194:[{"nombre":"Up (Original Motion Picture Soundtrack)", "artista":"Various Artists", "genero":"Soundtrack"}],
            195:[{"nombre":"Elemental (Original Motion Picture Soundtrack)", "artista":"Various Artists", "genero":"Soundtrack"}],
            196:[{"nombre":"Beam Me Up Scotty", "artista":"Nicki Minaj", "genero":"Hip-Hop"}],
            197:[{"nombre":"Queen", "artista":"Nicki Minaj", "genero":"Hip-Hop"}],
            198:[{"nombre":"The Pinkprint", "artista":"Nicki Minaj", "genero":"Hip-Hop"}],
            199:[{"nombre":"Pink Friday...Roman Reloaded", "artista":"Nicki Minaj", "genero":"Hip-Hop"}],
            200:[{"nombre":"Queen Radio: Volume 1", "artista":"Nicki Minaj", "genero":"Hip-Hop"}]}

@APIGetCD.get("/CD/Taylor")
async def TaylorSwift(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Midnights", "artista":"Taylor Swift", "genero":"Pop"}],
            2:[{"nombre":"reputation", "artista":"Taylor Swift", "genero":"Pop"}],
            3:[{"nombre":"Lover", "artista":"Taylor Swift", "genero":"Pop"}],
            4:[{"nombre":"1989", "artista":"Taylor Swift", "genero":"Pop"}],
            5:[{"nombre":"Taylor Swift", "artista":"Taylor Swift", "genero":"Country"}],
            6:[{"nombre":"Fearless", "artista":"Taylor Swift", "genero":"Country"}],
            7:[{"nombre":"Speak Now", "artista":"Taylor Swift", "genero":"Country"}],
            8:[{"nombre":"Red", "artista":"Taylor Swift", "genero":"Pop"}],
            9:[{"nombre":"folklore", "artista":"Taylor Swift", "genero":"Indie"}],
            10:[{"nombre":"evermore", "artista":"Taylor Swift", "genero":"Indie"}]}

@APIGetCD.get("/CD/ROSALIA")
async def Rosalia(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Los Angeles", "artista":"ROSALIA", "genero":"Indie"}],
            2:[{"nombre":"El Mal Querer", "artista":"ROSALIA", "genero":"Alternative"}],
            3:[{"nombre":"MOTOMAMI", "artista":"ROSALIA", "genero":"Pop"}]}

@APIGetCD.get("/CD/Taylor/Pop")
async def TaylorPop(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Midnights", "artista":"Taylor Swift", "genero":"Pop"}],
            2:[{"nombre":"reputation", "artista":"Taylor Swift", "genero":"Pop"}],
            3:[{"nombre":"Lover", "artista":"Taylor Swift", "genero":"Pop"}],
            4:[{"nombre":"1989", "artista":"Taylor Swift", "genero":"Pop"}],
            8:[{"nombre":"Red", "artista":"Taylor Swift", "genero":"Pop"}]}

@APIGetCD.get("/CD/ROSALIA/Pop")
async def RosaliaPop(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"MOTOMAMI", "artista":"ROSALIA", "genero":"Pop"}]}

@APIGetCD.get("/CD/LDR")
async def LDR(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Did you know that there's a tunnel under Ocean Blvd", "artista":"Lana del Rey", "genero":"Alternative"}],
            2:[{"nombre":"Blue Banisters", "artista":"Lana del Rey", "genero":"Alternative"}],
            3:[{"nombre":"Chemtrails Over The Country Club", "artista":"Lana del Rey", "genero":"Alternative"}],
            4:[{"nombre":"Norman Fucking Rockwell", "artista":"Lana del Rey", "genero":"Alternative"}],
            5:[{"nombre":"Lust For Life", "artista":"Lana del Rey", "genero":"Alternative"}],
            6:[{"nombre":"Honeymoon", "artista":"Lana del Rey", "genero":"Alternative"}],
            7:[{"nombre":"Ultraviolence", "artista":"Lana del Rey", "genero":"Alternative"}],
            8:[{"nombre":"Born to Die", "artista":"Lana del Rey", "genero":"Alternative"}],
            9:[{"nombre":"Paradise", "artista":"Lana del Rey", "genero":"Alternative"}]}

@APIGetCD.get("/CD/BebeRexha")
async def BebeRexha(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"I Don't Wanna Grow Up", "artista":"Bebe Rexha", "genero":"Pop"}],
            2:[{"nombre":"All Your Fault Pt. 1", "artista":"Bebe Rexha", "genero":"Pop"}],
            3:[{"nombre":"All Your Fault Pt. 2", "artista":"Bebe Rexha", "genero":"Pop"}],
            4:[{"nombre":"Expectations", "artista":"Bebe Rexha", "genero":"Pop"}],
            5:[{"nombre":"Better Mistakes", "artista":"Bebe Rexha", "genero":"Pop"}],
            6:[{"nombre":"Bebe", "artista":"Bebe Rexha", "genero":"Pop"}]}

@APIGetCD.get("/CD/Gaga")
async def Gaga(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"A Star Is Born Soundtrack", "artista":"Lady Gaga", "genero":"Soundtrack"}],
            2:[{"nombre":"Love For Sale (Deluxe)", "artista":"Lady Gaga", "genero":"Jazz"}],
            3:[{"nombre":"Chromatica", "artista":"Lady Gaga", "genero":"Pop"}],
            4:[{"nombre":"Joanne", "artista":"Lady Gaga", "genero":"Indie"}],
            5:[{"nombre":"Cheek to Cheek", "artista":"Lady Gaga", "genero":"Jazz"}],
            6:[{"nombre":"ARTPOP", "artista":"Lady Gaga", "genero":"Pop"}],
            7:[{"nombre":"Born this Way", "artista":"Lady Gaga", "genero":"Pop"}],
            8:[{"nombre":"The Fame Monster", "artista":"Lady Gaga", "genero":"Pop"}],
            9:[{"nombre":"The Fame", "artista":"Lady Gaga", "genero":"Pop"}]}

@APIGetCD.get("/CD/Gaga/Pop")
async def GagaPop(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Chromatica", "artista":"Lady Gaga", "genero":"Pop"}],
            2:[{"nombre":"ARTPOP", "artista":"Lady Gaga", "genero":"Pop"}],
            3:[{"nombre":"Born this Way", "artista":"Lady Gaga", "genero":"Pop"}],
            4:[{"nombre":"The Fame Monster", "artista":"Lady Gaga", "genero":"Pop"}],
            5:[{"nombre":"The Fame", "artista":"Lady Gaga", "genero":"Pop"}]}

@APIGetCD.get("/CD/Poppy")
async def Poppy(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"Bubblebath", "artista":"Poppy", "genero":"Pop"}],
            2:[{"nombre":"Poppy.Computer", "artista":"Poppy", "genero":"Pop"}],
            3:[{"nombre":"Am I a Girl?", "artista":"Poppy", "genero":"Pop"}],
            4:[{"nombre":"Choke", "artista":"Poppy", "genero":"Experimental"}],
            5:[{"nombre":"I Disagree", "artista":"Poppy", "genero":"Rock"}],
            6:[{"nombre":"A Very Poppy Christmas", "artista":"Poppy", "genero":"Rock"}],
            7:[{"nombre":"EAT (NXT Soundtrack)", "artista":"Poppy", "genero":"Rock"}],
            8:[{"nombre":"Flux", "artista":"Poppy", "genero":"Rock"}],
            9:[{"nombre":"Stagger", "artista":"Poppy", "genero":"Rock"}],
            10:[{"nombre":"Knockoff", "artista":"Poppy", "genero":"Rock"}]}

@APIGetCD.get("/CD/Poppy/Rock")
async def PoppyRock(): # asíncrona para que siempre esté disponible
    return {1:[{"nombre":"I Disagree", "artista":"Poppy", "genero":"Rock"}],
            2:[{"nombre":"A Very Poppy Christmas", "artista":"Poppy", "genero":"Rock"}],
            3:[{"nombre":"EAT (NXT Soundtrack)", "artista":"Poppy", "genero":"Rock"}],
            4:[{"nombre":"Flux", "artista":"Poppy", "genero":"Rock"}],
            5:[{"nombre":"Stagger", "artista":"Poppy", "genero":"Rock"}],
            6:[{"nombre":"Knockoff", "artista":"Poppy", "genero":"Rock"}]}


# LEVANTAR EL SERVIDOR UVICORN
# uvicorn [nombre_archivo]:[nombre_objeto] --reload

# entrar a la direccion 127.0.0.1:8000